config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :characters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
    validates :name, presence: true, length: {minimum: 4, maximun: 100} 
    validates :location, presence: true, length: {minimum: 4, maximun: 100} 
    validates :house, presence: true, length: {minimum: 4, maximun: 100} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
    before_action :set_character, only: [:show, :edit, :update, :destroy]

    def show    
    end

    def index
        @characters = Character.all
    end

    def new
        @character = Character.new
    end

    def edit
        
    end

    def create
        @character = Character.new(character_params)
        if @character.save
            flash[:notice] = "character was created successfully."
            redirect_to @character
        else
            render :new, status: 422
        end
    end

    def update
        if @character.update(character_params)
            flash[:notice] = "character was update successfully"
            redirect_to @character
        else
            render 'edit'
        end
    end

    def destroy
        @character.destroy
        redirect_to characters_path
    end
    # refactorizamos el codigo con el metodo set_movie
    private
    def set_character
        @character = Character.find(params[:id])
    end

    def character_params
        params.require(:character).permit(:name, :location, :house)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/characters/_form.html.erb
<% if @character.errors.any? %>
    <h2>The following errors prevented the character from being saved</h2>
    <ul>
        <% @character.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @character, local: true) do |f|%>
    <div class="mb-3">
        <%= f.label :name, class: "form-label" %><br/>
        <%= f.text_field :name, class:"form-control" %>
    </div>

    <div class="mb-3">
        <%= f.label :location, class: "form-label" %><br/>
        <%= f.text_field :location, class:"form-control" %>
    </div>

    <div class="mb-3">
        <%= f.label :house, class: "form-label" %><br/>
        <%= f.text_field :house, class:"form-control" %>
    </div>

    <div class="mb-3 ">
        <%= f.submit %>
    </div>
<% end %>

app/views/characters/edit.html.erb
<div class = "container mt-3">
    <h1>Edit Documentary</h1>
    <%= render 'form'%>
    <p>
        <%= link_to 'Create new character', new_character_path, class: "btn btn-primary"%>
    </p>

    <p>
        <%= link_to 'Return to characters films listing', characters_path, class: "btn btn-primary"%>
    </p>
</div>

app/views/characters/index.html.erb
<div class="container">
    <h1 class="mt-3">Charaters Index</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Synopsis</th>
                <th>Director</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @characters.each do |character|%>
            <tr>
                <td><%= character.name%></td>
                <td><%= character.location%></td>
                <td><%= character.house%></td>
                <td><%= link_to 'Show', character_path(character), class: "btn btn-primary"%></td>
                <td><%= button_to 'Delete', character_path(character), method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-primary"  %></td>
                <td><%= link_to 'Edit', edit_character_path(character), method: :update, class: "btn btn-primary" %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <p>
        <%= link_to 'Create new character', new_character_path, class: "btn btn-primary m-2"%>
    </p>
</div>

app/views/characters/new.html.erb
<div class="container mt-3">

    <h1>Create a new Character</h1>

    <%= render 'form'%>

    <%= link_to 'Return to character listing', characters_path, class: "btn btn-primary"%>
</div>

app/views/characters/show.html.erb
<div class="card border-success mb-3 text-center container mt-4" style="max-width: 18rem;">
    <div class="card-header bg-transparent border-success">
      <strong>Name: </strong><%= @character.name%>
    </div>
    <div class="card-body text-success">
      <h5 class="card-title">
        <strong>location: </strong>
        <%= @character.location%>
      </h5>
      <p class="card-text">
        <strong>house: </strong>
        <%= @character.house%>
      </p>
    </div>
    <div class="card-footer bg-transparent border-success">Howarts</div>
      <%= link_to 'Edit' , edit_character_path(@character), class: "btn btn-primary m-2" %>
      <%= button_to 'Delete' , character_path(@character), method: :delete, data: {confirm: "Are you sure" },
        class: "btn btn-primary m-2" %>
      <%= link_to 'Return to movies listing' , characters_path, class: "btn btn-primary m-2" %>
      <%= link_to 'Create new article' , new_character_path, class: "btn btn-primary m-2" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HowartsRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container text-center">
    <h1>Hogwarts</h1>
    <div class="row">
        <%= image_tag('howarts.png', class:"img-thumbnail col-8 me-1") %>
        <div class="col">
            <p class="fw-semibold ">donde la magia se convierte en realidad y los sueños se hacen tangibles. Este majestuoso castillo, ubicado en un lugar secreto, ha cautivado a generaciones de brujas y magos con su esplendor arquitectónico y su ambiente lleno de misterio. Aquí, las aulas cobran vida con hechizos y pociones, los pasillos susurran historias antiguas y los retratos mágicos observan cada paso que das.</p>
            <p class="fw-semibold ">En Hogwarts, las amistades se forjan entre estudiantes de distintas casas, mientras se enfrentan a desafíos y pruebas que pondrán a prueba su valentía, sabiduría, lealtad y astucia. Los profesores son guías sabios y enigmáticos, expertos en sus respectivas materias y dispuestos a ayudar a los jóvenes brujos y brujas a desatar su verdadero potencial.</p>
            <%= link_to 'Integrantes de Hogwarts', characters_path, class: "btn btn-success"%>
        </div>
        
    </div>
    
</div>